name: UI tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    # Set to ubuntu-22.04 due to: https://github.com/ReactiveCircus/android-emulator-runner/issues/400
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run UI tests
        uses: ReactiveCircus/android-emulator-runner@v2.33.0
        with:
          api-level: 29
          target: default
          arch: x86
          profile: Nexus 6
          disable-animations: true
          script: ./gradlew connectedCheck

      - uses: actions/upload-artifact@v4
        with:
          name: ui-test-results.zip
          path: ./**/build/reports/ui-tests/